export const WorkOutSplit = [
  {
    id: "01",
    split: "PPL",
  },
  {
    id: "02",
    split: "BRO SPLIT",
  },
  {
    id: "03",
    split: "ARNOLD SPLIT",
  },
  {
    id: "04",
    split: "UPPER AND LOWER",
  },
];

export const exerciseList = [
  // PUSH
  {
    id: "01",
    name: "TRICEPS",
    category: "PPL",
    image: require("./assets/Icons/TricepIcon.png"),
    color: "#fff",
    exercises: ["Katana Extension", "Cable Tricep Pushdown"],
  },
  {
    id: "02",
    name: "SHOULDERS",
    category: "PPL",
    image: require("./assets/Icons/ShoulderIcon.png"),
    color: "#fff",
    exercises: ["Lateral Raise", "Dumbbell Shoulder Press"],
  },
  {
    id: "03",
    name: "CHEST",
    category: "PPL",
    image: require("./assets/Icons/ChestIcon.png"),
    color: "#fff",
    exercises: [
      "Incline Dumbbell Press",
      "Machine Incline Press",
      "Dumbbell Bench Press",
      "Barbell Bench Press",
      "High-To-Low Cables",
      "Dips",
    ],
  },
  // PULL
  {
    id: "04",
    name: "BACK",
    category: "PPL",
    image: require("./assets/Icons/BackIcon.png"),
    color: "#fff",
    exercises: ["Lat Pulldowns", "Chest Supported Dumbbell Row"],
  },
  {
    id: "05",
    name: "BICEPS",
    category: "PPL",
    image: require("./assets/Icons/BicepIcon.png"),
    color: "#fff",
    exercises: ["Incline Curls", "Hammer Curls", "Spider Curls"],
  },
  {
    id: "06",
    name: "REAR DELTS",
    category: "PPL",
    image: require("./assets/Icons/ShoulderIcon.png"),
    color: "#fff",
    exercises: ["Rear Delt Flies"],
  },
  // LEGS
  {
    id: "07",
    name: "LEGS",
    category: "PPL",
    image: require("./assets/Icons/LegIcon.png"),
    color: "#fff",
    exercises: [
      "Hack Squat",
      "Leg Extension",
      "Leg Curls",
      "Romanian Deadlifts",
      "Calf Raises",
    ],
  },
  //BRO Split
  {
    id: "08",
    name: "CHEST",
    category: "BRO SPLIT",
    image: require("./assets/Icons/ChestIcon.png"),
    color: "#fff",
    exercises: [
      "Dumbbell Bench Press",
      "Barbell Bench Press",
      "Incline Dumbbell Bench Press",
      "Barbell Incline Bench Press",
      "Dumbbell Chest Flies",
      "Dips",
    ],
  },
  {
    id: "09",
    name: "SHOULDERS",
    category: "BRO SPLIT",
    image: require("./assets/Icons/ShoulderIcon.png"),
    color: "#fff",
    exercises: [
      "Dumbbell Shoulder Press",
      "Dumbbell Lateral Raise",
      "Cable Lateral Raise",
      "Rear Delt Flies",
    ],
  },
  {
    id: "10",
    name: "LEGS",
    category: "BRO SPLIT",
    image: require("./assets/Icons/LegIcon.png"),
    color: "#fff",
    exercises: [
      "Hack Squat",
      "Leg Extension",
      "Leg Curls",
      "Romanian Deadlifts",
      "Calf Raises",
    ],
  },
  {
    id: "11",
    name: "ARMS",
    category: "BRO SPLIT",
    image: require("./assets/Icons/BicepIcon.png"),
    color: "#fff",
    exercises: [
      "Preacher Curls",
      "Incline Curls",
      "Hammer Curls",
      "Katana Extensions",
      "Cable Pulldowns",
      "Dips",
    ],
  },
  {
    id: "12",
    name: "BACK",
    category: "BRO SPLIT",
    image: require("./assets/Icons/BackIcon.png"),
    color: "#fff",
    exercises: [
      "Barbell Rows",
      "Chest Supported Rows",
      "Lat Pulldown",
      "Pull Ups",
      "Deadlift",
    ],
  },
  //ARNOLD_SPLIT Split
  {
    id: "13",
    name: "CHEST",
    category: "ARNOLD SPLIT",
    image: require("./assets/Icons/ChestIcon.png"),
    color: "#fff",
    exercises: ["Dumbbell Bench Press", "Incline Dumbbell Bench Press", "Dips"],
  },
  {
    id: "14",
    name: "BACK",
    category: "ARNOLD SPLIT",
    image: require("./assets/Icons/BackIcon.png"),
    color: "#fff",
    exercises: ["Pull Ups", "Dumbbell Rows", "Barbell Rows"],
  },
  {
    id: "15",
    name: "ABS",
    category: "ARNOLD SPLIT",
    image: require("./assets/Icons/AbsIcon.png"),
    color: "#fff",
    exercises: [
      "Crunches",
      "Flutter Kicks",
      "Planks",
      "Bicycle Crunches",
      "Leg Raise",
    ],
  },
  // UPPER
  {},
];
